#!/usr/bin/env bash

puppet apply --environment=proles --hiera_config /vagrant/hiera.yaml --modulepath /etc/puppetlabs/code/environments/proles/modules:/puppet/sitemodules/:/puppet/oldmodules/ /puppet/manifests/
